name: release
on: [workflow_dispatch] # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
jobs:
  tag:
    name: Publish by date
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tag
        run: git tag $(date -Idate)
