name: release
on: [workflow_dispatch] # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
jobs:
  tag:
    name: Publish by date
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Resolve TAG
        run: |
          export TAG=$(date -Idate)
          echo "Resolved tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Tag
        run: git tag $TAG
      - name: Push
        run: git push origin tag $TAG
