name: onpush
on: [push] # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
jobs:
  test:
    name: Integration pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make build
      - name: Log in to Docker Hub
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name == 'master'}}
        uses: docker/login-action@v3
        with:
          username: antonmarin
          password: ${{ secrets.DOCKER_PUBLISH_TOKEN }}  
      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name == 'master'}}
        run: make PUBLIC_TAG=${{ github.ref_name }} publish
